version: "3.7"
name: app
services:
  mysqldatabase:
    image: mysql
    container_name: mysqldatabase
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'images'
      MYSQL_ROOT_PASSWORD: '12345'
    volumes:
      - data:/var/lib/mysql
    networks:
      - myprivatenet
  nodeapp:
    container_name: nodeapp
    image: images-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysqldatabase
    restart: on-failure
    networks:
      - myprivatenet
  angularapp:
    container_name: angularapp
    image: images-frontend
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - myprivatenet

volumes:
  data: {}

networks:
  myprivatenet:
    name: myprivatenet
    driver: bridge
